# For more information on MEX files, see
# http://www.mathworks.com/access/helpdesk/help/techdoc/matlab_external/f29502.html

set(CMAKE_LIBRARY_PATH_FLAG "-L")
set(CMAKE_LINK_LIBRARY_FLAG "-l")
set(CMAKE_INCLUDE_FLAG_C "-I")
set(CMAKE_INCLUDE_FLAG_CXX "-I")
set(CMAKE_INCLUDE_FLAG_C_SEP "")
set(CMAKE_INCLUDE_FLAG_CXX_SEP "")

# User should specify compiler flags in their mex options file, not with cmake
# configuration!
set(CMAKE_C_FLAGS_DEBUG_INIT "-g")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-g")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "")
set(CMAKE_C_FLAGS_RELEASE_INIT "-O")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "")
set(CMAKE_SHARED_LIBRARY_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_CXX_FLAGS "")

set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_SHARED_MODULE_PREFIX "")

set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> -outdir <OBJECT_DIR> <FLAGS> -c <SOURCE>")
set(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER>  -outdir <OBJECT_DIR> <FLAGS> -c <SOURCE>")
set(CMAKE_C_CREATE_SHARED_MODULE
	"<CMAKE_C_COMPILER> <LINK_FLAGS> -output <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_CXX_CREATE_SHARED_MODULE
	"<CMAKE_CXX_COMPILER> -cxx <LINK_FLAGS> -output <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_C_CREATE_SHARED_LIBRARY ${CMAKE_C_CREATE_SHARED_MODULE})
set(CMAKE_CXX_CREATE_SHARED_LIBRARY ${CMAKE_CXX_CREATE_SHARED_MODULE})

# Only creates shared libraries to be loaded by Matlab, no standalone
# executables.
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_C_LINK_EXECUTABLE "ERROR: mex compiler only creates shared libraries/modules for Matlab")
set(CMAKE_CXX_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})
set(CMAKE_C_CREATE_STATIC_LIBRARY ${CMAKE_C_LINK_EXECUTABLE})
set(CMAKE_CXX_CREATE_STATIC_LIBRARY ${CMAKE_C_LINK_EXECUTABLE})

# http://thread.gmane.org/gmane.comp.programming.tools.cmake.user/13192/focus=13277
set(CMAKE_C_OUTPUT_EXTENSION_REPLACE 1)
set(CMAKE_CXX_OUTPUT_EXTENSION_REPLACE 1)

