if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
  set(CMAKE_SHARED_LIBRARY_SUFFIX ".mexw64")
  set(CMAKE_SHARED_MODULE_SUFFIX  ".mexw64")
elseif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86")
  set(CMAKE_SHARED_LIBRARY_SUFFIX ".mexw32")
  set(CMAKE_SHARED_MODULE_SUFFIX  ".mexw32")
endif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")

include(Platform/mex)

